config/routes.rb
Rails.application.routes.draw do
  root 'home#index'
  get 'home/index'
  resources :vehicles
  resources :vehicle_category_and_payments
  resources :routes
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/route.rb
class Route < ApplicationRecord
end

app/models/vehicle.rb
class Vehicle < ApplicationRecord
  belongs_to :vehicle_category_and_payment
  validates :license_plate, uniqueness: true
end

app/models/vehicle_category_and_payment.rb
class VehicleCategoryAndPayment < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/routes_controller.rb
class RoutesController < ApplicationController
  before_action :set_route, only: [:show, :edit, :update, :destroy]

  # GET /routes
  # GET /routes.json
  def index
    @routes = Route.all
  end

  # GET /routes/1
  # GET /routes/1.json
  def show
  end

  # GET /routes/new
  def new
    @route = Route.new
  end

  # GET /routes/1/edit
  def edit
  end

  # POST /routes
  # POST /routes.json
  def create
    @route = Route.new(route_params)

    respond_to do |format|
      if @route.save
        format.html { redirect_to @route, notice: 'Route was successfully created.' }
        format.json { render :show, status: :created, location: @route }
      else
        format.html { render :new }
        format.json { render json: @route.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /routes/1
  # PATCH/PUT /routes/1.json
  def update
    respond_to do |format|
      if @route.update(route_params)
        format.html { redirect_to @route, notice: 'Route was successfully updated.' }
        format.json { render :show, status: :ok, location: @route }
      else
        format.html { render :edit }
        format.json { render json: @route.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /routes/1
  # DELETE /routes/1.json
  def destroy
    @route.destroy
    respond_to do |format|
      format.html { redirect_to routes_url, notice: 'Route was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_route
      @route = Route.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def route_params
      params.require(:route).permit(:origin, :destination, :distance, :tollbooths_2_to_4_edges, :tollbooths_5_to_6_edges, :days)
    end
end

app/controllers/vehicle_category_and_payments_controller.rb
class VehicleCategoryAndPaymentsController < ApplicationController
  before_action :set_vehicle_category_and_payment, only: [:show, :edit, :update, :destroy]

  # GET /vehicle_category_and_payments
  # GET /vehicle_category_and_payments.json
  def index
    @vehicle_category_and_payments = VehicleCategoryAndPayment.all
  end

  # GET /vehicle_category_and_payments/1
  # GET /vehicle_category_and_payments/1.json
  def show
  end

  # GET /vehicle_category_and_payments/new
  def new
    @vehicle_category_and_payment = VehicleCategoryAndPayment.new
  end

  # GET /vehicle_category_and_payments/1/edit
  def edit
  end

  # POST /vehicle_category_and_payments
  # POST /vehicle_category_and_payments.json
  def create
    @vehicle_category_and_payment = VehicleCategoryAndPayment.new(vehicle_category_and_payment_params)

    respond_to do |format|
      if @vehicle_category_and_payment.save
        format.html { redirect_to @vehicle_category_and_payment, notice: 'Vehicle category and payment was successfully created.' }
        format.json { render :show, status: :created, location: @vehicle_category_and_payment }
      else
        format.html { render :new }
        format.json { render json: @vehicle_category_and_payment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /vehicle_category_and_payments/1
  # PATCH/PUT /vehicle_category_and_payments/1.json
  def update
    respond_to do |format|
      if @vehicle_category_and_payment.update(vehicle_category_and_payment_params)
        format.html { redirect_to @vehicle_category_and_payment, notice: 'Vehicle category and payment was successfully updated.' }
        format.json { render :show, status: :ok, location: @vehicle_category_and_payment }
      else
        format.html { render :edit }
        format.json { render json: @vehicle_category_and_payment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /vehicle_category_and_payments/1
  # DELETE /vehicle_category_and_payments/1.json
  def destroy
    @vehicle_category_and_payment.destroy
    respond_to do |format|
      format.html { redirect_to vehicle_category_and_payments_url, notice: 'Vehicle category and payment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_vehicle_category_and_payment
      @vehicle_category_and_payment = VehicleCategoryAndPayment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def vehicle_category_and_payment_params
      params.require(:vehicle_category_and_payment).permit(:category, :payment_per_km, :payment_per_return_km)
    end
end

app/controllers/vehicles_controller.rb
class VehiclesController < ApplicationController
  before_action :set_vehicle, only: [:show, :edit, :update, :destroy]

  # GET /vehicles
  # GET /vehicles.json
  def index
    @vehicles = Vehicle.all
  end

  # GET /vehicles/1
  # GET /vehicles/1.json
  def show
  end

  # GET /vehicles/new
  def new
    @vehicle = Vehicle.new
  end

  # GET /vehicles/1/edit
  def edit
  end

  # POST /vehicles
  # POST /vehicles.json
  def create
    @vehicle = Vehicle.new(vehicle_params)

    respond_to do |format|
      if @vehicle.save
        format.html { redirect_to @vehicle, notice: 'Vehicle was successfully created.' }
        format.json { render :show, status: :created, location: @vehicle }
      else
        format.html { render :new }
        format.json { render json: @vehicle.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /vehicles/1
  # PATCH/PUT /vehicles/1.json
  def update
    respond_to do |format|
      if @vehicle.update(vehicle_params)
        format.html { redirect_to @vehicle, notice: 'Vehicle was successfully updated.' }
        format.json { render :show, status: :ok, location: @vehicle }
      else
        format.html { render :edit }
        format.json { render json: @vehicle.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /vehicles/1
  # DELETE /vehicles/1.json
  def destroy
    @vehicle.destroy
    respond_to do |format|
      format.html { redirect_to vehicles_url, notice: 'Vehicle was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_vehicle
      @vehicle = Vehicle.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def vehicle_params
      params.require(:vehicle).permit(:brand, :vehicle_type, :year, :performance_km_fuel, :economic, :edges, :license_plate, :vehicle_category_and_payment_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/routes_helper.rb
module RoutesHelper
end

app/helpers/vehicle_category_and_payments_helper.rb
module VehicleCategoryAndPaymentsHelper
end

app/helpers/vehicles_helper.rb
module VehiclesHelper
end

app/views/home/index.html.erb
<div class="container">
  <h1>Cotizador de Gastos de Operacion</h1>
  <hr>
  <%= form_tag do %>
    <div class="row">
      <div class="col-sm">
        <%= label_tag :vehicle, 'Vehículo' %> 
        <%= select_tag :vehicle, options_for_select( Vehicle.all.collect { |v| ["#{v.license_plate || NANANA} - #{v.year} - #{v.brand} - #{v.vehicle_type}", v.id]} ), {include_blank: "Selecciona un vehículo...", id: 'vehicle_select', class: 'form-control' } %>
        <div id="vehicleInfo" class="calc-info">
        </div>
      </div>

      <div class="col-sm">
        <%= label_tag :route, 'Ruta' %> 
        <%= select_tag :route, options_for_select( Route.all.collect { |r| ["#{r.origin} - #{r.destination}", r.id]} ), {include_blank: "Selecciona una ruta...", id: 'route_select', class: 'form-control' } %>
        <div id="routeInfo" class="calc-info">
        </div>
      </div>
    </div>

    <div class="row ">
      <div class="col-sm-2">
        <%= label_tag :days, 'Dias' %> 
        <%= number_field_tag :days, {}, class: 'form-control' %>
        <div id="vehicleInfo" class="calc-info">
        </div>
      </div>

      <div class="col-sm-2 text-center">
        <span>Comida por dias</span>
        <br><br>
        <strong>$150.00</strong>
      </div>

      <div class="col-sm-2">
        <%= label_tag :fuel_by_liter, 'Costo Combustible/Lt' %> 
        <%= number_field_tag :fuel_by_liter, {}, class: 'form-control' %>
        <div id="vehicleInfo" class="calc-info">
        </div>
      </div>

      <div class="col-sm-2 text-center">
        <span>Litros de ruta</span>
        <br><br>
        <strong id="routeLiters"></strong>
      </div>

      <div class="col-sm-4 text-right">
        <%= submit_tag 'Calcular', id: 'calcButton', class: 'btn btn-primary btn-lg' %>
      </div>
    </div>

  <% end %>


  <div id="resultsContainer" class="row">
      <div class="col-sm-2 text-center">
        <h4 id="resumeDistance"></h4>
        <span>Pago distancia</span>
      </div>

      <div class="col-sm-2 text-center">
       <h4 id="resumeTollbooths"></h4>
        <span>Casetas</span>
      </div>

      <div class="col-sm-2 text-center">
       <h4 id="resumeFood"></h4>
        <span>Comida</span>
      </div>

      <div class="col-sm-2 text-center">
       <h4 id="resumeFuel"></h4>
        <span>Combustible</span>
      </div>

       <div class="col-sm-2 text-center">
       <h4><strong id="resumeOperation"></strong></h4>
        <span>Costo Operación</span>
      </div>
    </div>

</div>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="#">COTIZADOR DE OPERACION</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active">
        <%= link_to 'Cotizacion', root_path, class: 'nav-link' %>
      </li>
      <li class="nav-item">
        <%= link_to "Vehículos", vehicles_path, class: 'nav-link' %>
      </li>
      <li class="nav-item">
        <%= link_to "Categoría y Paga", vehicle_category_and_payments_path, class: 'nav-link' %>
      </li>
      <li class="nav-item">
        <%= link_to "Rutas", routes_path, class: 'nav-link' %>
      </li>
    </ul>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Myapp</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
  
    <%= render 'layouts/header' %>

    <%= yield %>
  </body>
</html>

app/views/routes/_form.html.erb
<%= form_with(model: route, local: true) do |form| %>
  <% if route.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(route.errors.count, "error") %> prohibited this route from being saved:</h2>

      <ul>
      <% route.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :Origen %>
    <%= form.text_field :origin %>
  </div>

  <div class="field">
    <%= form.label :Destino %>
    <%= form.text_field :destination %>
  </div>

  <div class="field">
    <%= form.label :Distancia %>
    <%= form.text_field :distance %>
  </div>

  <div class="field">
    <%= form.label :Caseta_2_a_4_ejes %>
    <%= form.number_field :tollbooths_2_to_4_edges %>
  </div>

  <div class="field">
    <%= form.label :Caseta_5_a_6_ejes %>
    <%= form.number_field :tollbooths_5_to_6_edges %>
  </div>

  <div class="field">
    <%= form.label :Dias %>
    <%= form.number_field :days %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/routes/edit.html.erb
<h1>Editing Route</h1>

<%= render 'form', route: @route %>

<%= link_to 'Show', @route %> |
<%= link_to 'Back', routes_path %>

app/views/routes/index.html.erb
<div class="container">
  <h1>Rutas por viaje</h1>

  <table class="table">
    <thead>
      <tr>
        <th>Origen</th>
        <th>Destino</th>
        <th>Distancia</th>
        <th>Casetas 2-4 Ejes</th>
        <th>Casetas 5-6 Ejes</th>
        <th>Dias</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @routes.each do |route| %>
        <tr>
          <td><%= route.origin %></td>
          <td><%= route.destination %></td>
          <td><%= route.distance %></td>
          <td><%= route.tollbooths_2_to_4_edges %></td>
          <td><%= route.tollbooths_5_to_6_edges %></td>
          <td><%= route.days %></td>
          <td><%= link_to 'Show', route %></td>
          <td><%= link_to 'Edit', edit_route_path(route) %></td>
          <td><%= link_to 'Destroy', route, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <br>

  <%= link_to 'Agregar Ruta', new_route_path %>
</div>

app/views/routes/new.html.erb
<h1>Crear nueva RUTA</h1>

<%= render 'form', route: @route %>

<%= link_to 'Back', routes_path %>

app/views/routes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Origen:</strong>
  <%= @route.origin %>
</p>

<p>
  <strong>Destino:</strong>
  <%= @route.destination %>
</p>

<p>
  <strong>Distancia:</strong>
  <%= @route.distance %>
</p>

<p>
  <strong>Casetas_4_ejes:</strong>
  <%= @route.tollbooths_2_to_4_edges %>
</p>

<p>
  <strong>Casetas_6_ejes:</strong>
  <%= @route.tollbooths_5_to_6_edges %>
</p>

<p>
  <strong>Days:</strong>
  <%= @route.days %>
</p>

<%= link_to 'Edit', edit_route_path(@route) %> |
<%= link_to 'Back', routes_path %>

app/views/vehicle_category_and_payments/_form.html.erb
<%= form_with(model: vehicle_category_and_payment, local: true) do |form| %>
  <% if vehicle_category_and_payment.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(vehicle_category_and_payment.errors.count, "error") %> prohibited this vehicle_category_and_payment from being saved:</h2>

      <ul>
      <% vehicle_category_and_payment.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :category %>
    <%= form.text_field :category %>
  </div>

  <div class="field">
    <%= form.label :payment_per_km %>
    <%= form.text_field :payment_per_km %>
  </div>

  <div class="field">
    <%= form.label :payment_per_return_km %>
    <%= form.text_field :payment_per_return_km %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/vehicle_category_and_payments/edit.html.erb
<h1>Editing Vehicle Category And Payment</h1>

<%= render 'form', vehicle_category_and_payment: @vehicle_category_and_payment %>

<%= link_to 'Show', @vehicle_category_and_payment %> |
<%= link_to 'Back', vehicle_category_and_payments_path %>

app/views/vehicle_category_and_payments/index.html.erb
<div class="container">
  <h1> CATEGORIA DE VEHICULO Y PAGOS</h1>

  <table class="table">
    <thead>
      <tr>
        <th>Categoria</th>
        <th>Pago por KM de Ida</th>
        <th>Pago por KM de regreso</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @vehicle_category_and_payments.each do |vehicle_category_and_payment| %>
        <tr>
          <td><%= vehicle_category_and_payment.category %></td>
          <td><%= vehicle_category_and_payment.payment_per_km %></td>
          <td><%= vehicle_category_and_payment.payment_per_return_km %></td>
          <td><%= link_to 'Show', vehicle_category_and_payment %></td>
          <td><%= link_to 'Edit', edit_vehicle_category_and_payment_path(vehicle_category_and_payment) %></td>
          <td><%= link_to 'Destroy', vehicle_category_and_payment, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <br>

  <%= link_to 'Agregar categoria de pago', new_vehicle_category_and_payment_path %>
</div>

app/views/vehicle_category_and_payments/new.html.erb
<h1>New Vehicle Category And Payment</h1>

<%= render 'form', vehicle_category_and_payment: @vehicle_category_and_payment %>

<%= link_to 'Back', vehicle_category_and_payments_path %>

app/views/vehicle_category_and_payments/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Category:</strong>
  <%= @vehicle_category_and_payment.category %>
</p>

<p>
  <strong>Payment per km:</strong>
  <%= @vehicle_category_and_payment.payment_per_km %>
</p>

<p>
  <strong>Payment per return km:</strong>
  <%= @vehicle_category_and_payment.payment_per_return_km %>
</p>

<%= link_to 'Edit', edit_vehicle_category_and_payment_path(@vehicle_category_and_payment) %> |
<%= link_to 'Back', vehicle_category_and_payments_path %>

app/views/vehicles/_form.html.erb
<%= form_with(model: vehicle, local: true) do |form| %>
  <% if vehicle.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(vehicle.errors.count, "error") %> prohibited this vehicle from being saved:</h2>

      <ul>
      <% vehicle.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :ECO %>
    <%= form.text_field :economic %>
  </div>
  <div class="field">
    <%= form.label :MARCA %>
    <%= form.text_field :brand %>
  </div>

  <div class="field">
    <%= form.label :TIPO %>
    <%= form.text_field :vehicle_type %>
  </div>

  <div class="field">
    <%= form.label :AÑO %>
    <%= form.number_field :year %>
  </div>
  <div class="field">
    <%= form.label :Rendimiento%>
    <%= form.number_field :performance_km_fuel %>
  </div>

  <div class="field">
    <%= form.label :EJES %>
    <%= form.select :edges, %w[2 3 4 5 6] %>
  </div>
  <div class="field">
    <%= form.label :PAGO_POR_CATEGORIA_DE_VEHICULO %>
    <%= form.select :vehicle_category_and_payment_id, VehicleCategoryAndPayment.all.collect{ |v| [v.category, v.id] } %>
  </div>

  <div class="field">
    <%= form.label :license_plate, 'Placas' %>
    <%= form.text_field :license_plate %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/vehicles/edit.html.erb
<h1>Editing Vehicle</h1>

<%= render 'form', vehicle: @vehicle %>

<%= link_to 'Show', @vehicle %> |
<%= link_to 'Back', vehicles_path %>

app/views/vehicles/index.html.erb
<div class="container">
  
<h1>Parque Vehicular</h1>
  <table class="table">
    <thead>
      <tr>
        <th>ECO</th>
        <th>MARCA</th>
        <th>TIPO</th>
        <th>AÑO</th>
        <th>Rendimiento KM/COMB</th>
        <th>PAGO DE VEHICULO POR CATEGORIA</th>
        <th>NUMERO DE EJES</th>
        <th>Placas</th>
        <th colspan="3"></th>
      </tr>
    </thead>

    <tbody>
      <% @vehicles.each do |vehicle| %>
        <tr>
          <td><%= vehicle.economic %></td>
          <td><%= vehicle.brand %></td>
          <td><%= vehicle.vehicle_type %></td>
          <td><%= vehicle.year %></td>
          <td><%= vehicle.performance_km_fuel %></td>
          <td><%= vehicle.vehicle_category_and_payment.category if vehicle.vehicle_category_and_payment.present? %></td>
          <td><%= vehicle.edges %></td>
          <td><%= vehicle.license_plate %></td>
          <td><%= link_to 'Show', vehicle %></td>
          <td><%= link_to 'Edit', edit_vehicle_path(vehicle) %></td>
          <td><%= link_to 'Destroy', vehicle, method: :delete, data: { confirm: 'Are you sure?' } %></td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <br>

  <%= link_to 'Agregar Vehiculo', new_vehicle_path %>
</div>

app/views/vehicles/new.html.erb
<h1>Nuevo Vehiculo </h1>

<%= render 'form', vehicle: @vehicle %>

<%= link_to 'Atras', vehicles_path %>

app/views/vehicles/show.html.erb
<p id="notice"><%= notice %></p>
<p>
  <strong>ECO:</strong>
  <%= @vehicle.economic %>
</p>
<p>
  <strong>Brand:</strong>
  <%= @vehicle.brand %>
</p>

<p>
  <strong>Type:</strong>
  <%= @vehicle.vehicle_type %>
</p>

<p>
  <strong>Year:</strong>
  <%= @vehicle.year %>
</p>
<p>
  <strong>Rendimiento KM/COMB:</strong>
  <%= @vehicle.performance_km_fuel %>
</p>
<p>
  <strong>Ejes:</strong>
  <%= @vehicle.edges %>
</p>

<p>
  <strong>Placas:</strong>
  <%= @vehicle.license_plate %>
</p>

<p>
  <strong>Vehicle category and payment:</strong>
  <%= @vehicle.vehicle_category_and_payment.category if @vehicle.vehicle_category_and_payment.present? %>
</p>

<%= link_to 'Edit', edit_vehicle_path(@vehicle) %> |
<%= link_to 'Back', vehicles_path %>